import { PrismaClient } from '@prisma/client'
import { hash } from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding database...')

  // Create admin user
  const adminPassword = await hash(process.env.ADMIN_PASSWORD || 'admin123', 12)
  const admin = await prisma.user.upsert({
    where: { email: process.env.ADMIN_EMAIL || 'admin@shopcrypto.co.za' },
    update: {},
    create: {
      email: process.env.ADMIN_EMAIL || 'admin@shopcrypto.co.za',
      name: 'Admin',
      password: adminPassword,
      role: 'ADMIN',
    },
  })
  console.log('Admin user created:', admin.email)

  // Create categories
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: 'new-miners' },
      update: {},
      create: {
        name: 'New Miners',
        slug: 'new-miners',
        description: 'Brand new ASIC miners from top manufacturers',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'second-hand-miners' },
      update: {},
      create: {
        name: 'Second Hand Miners',
        slug: 'second-hand-miners',
        description: 'Quality pre-owned miners at great prices',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'accessories' },
      update: {},
      create: {
        name: 'Accessories',
        slug: 'accessories',
        description: 'Cooling, cables, and mining essentials',
      },
    }),
  ])
  console.log('Categories created:', categories.map(c => c.name).join(', '))

  const [newMiners, secondHand, accessories] = categories

  // Create products - prices matched to market (Hashrate.co.za Dec 2024)
  const products = [
    // New Miners - S21 Series
    {
      name: 'Bitmain Antminer S21 200TH',
      slug: 's21-200th-crypto-asic-miner',
      price: 87320,
      compareAtPrice: 103999,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 5,
      isActive: true,
      isFeatured: true,
      images: ['/products/s21.jpg'],
      hashrate: '200 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3500W',
      description: 'The Bitmain Antminer S21 200TH is one of the most powerful Bitcoin miners available. With a hashrate of 200 TH/s and power efficiency of 17.5 J/TH, this miner delivers exceptional performance for serious mining operations.',
    },
    {
      name: 'Bitmain Antminer S21 195TH',
      slug: 's21-195th-crypto-asic-miner',
      price: 85340,
      compareAtPrice: 99999,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      isFeatured: true,
      images: ['/products/s21-190th.jpg'],
      hashrate: '195 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3380W',
      description: 'The Bitmain Antminer S21 195TH delivers outstanding Bitcoin mining performance with industry-leading efficiency.',
    },
    {
      name: 'Bitmain Antminer S21 188TH',
      slug: 's21-188th-crypto-asic-miner',
      price: 78140,
      compareAtPrice: 89999,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 4,
      isActive: true,
      images: ['/products/s21-190th.jpg'],
      hashrate: '188 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3290W',
      description: 'The Bitmain Antminer S21 188TH offers excellent hashrate at a competitive price point.',
    },
    {
      name: 'Bitmain Antminer S21 PRO 245TH',
      slug: 's21-pro-245th-crypto-asic-miner',
      price: 86100,
      compareAtPrice: 115000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      isFeatured: true,
      images: ['/products/s21.jpg'],
      hashrate: '245 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3680W',
      description: 'The ultimate Bitmain Antminer S21 PRO with 245 TH/s hashrate. Maximum Bitcoin mining power.',
    },
    {
      name: 'Bitmain Antminer S21 PRO 234TH',
      slug: 's21-pro-234th-crypto-asic-miner',
      price: 75100,
      compareAtPrice: 95000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      isFeatured: true,
      images: ['/products/s21.jpg'],
      hashrate: '234 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3510W',
      description: 'The flagship Bitmain Antminer S21 PRO with 234 TH/s hashrate. The most powerful consumer Bitcoin miner available.',
    },
    {
      name: 'Bitmain Antminer S21 PRO 220TH',
      slug: 's21-pro-220th-crypto-asic-miner',
      price: 68050,
      compareAtPrice: 85000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 4,
      isActive: true,
      images: ['/products/s21.jpg'],
      hashrate: '220 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3300W',
      description: 'High-performance S21 PRO with excellent efficiency at 15 J/TH.',
    },
    // S19 XP Series
    {
      name: 'Bitmain Antminer S19j XP 151TH',
      slug: 's19j-xp-151th-crypto-asic-miner',
      price: 81799,
      compareAtPrice: 99000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      isFeatured: true,
      images: ['/products/s19-xp-140th.png'],
      hashrate: '151 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3247W',
      description: 'The Bitmain Antminer S19j XP 151TH offers exceptional hashrate with improved power efficiency.',
    },
    {
      name: 'Bitmain Antminer S19 XP 141TH',
      slug: 's19-xp-141th-crypto-asic-miner',
      price: 39200,
      compareAtPrice: 65000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 4,
      isActive: true,
      images: ['/products/s19-xp-140th.png'],
      hashrate: '141 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3010W',
      description: 'The Bitmain Antminer S19 XP 141TH offers excellent hashrate with improved power efficiency for Bitcoin mining.',
    },
    // S19j Pro+ Series
    {
      name: 'Bitmain Antminer S19j Pro+ 120TH',
      slug: 's19j-pro-plus-120th',
      price: 32710,
      compareAtPrice: 45000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 6,
      isActive: true,
      images: ['/products/s19j-pro-plus-120th.png'],
      hashrate: '120 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '2760W',
      description: 'The Bitmain Antminer S19j Pro+ 120TH delivers solid performance and efficiency for Bitcoin mining operations.',
    },
    // S19K Pro Series
    {
      name: 'Bitmain Antminer S19K Pro 120TH',
      slug: 's19k-pro-120th-crypto-asic-miner',
      price: 23900,
      compareAtPrice: 35000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 8,
      isActive: true,
      isFeatured: true,
      images: ['/products/s19k-pro-120th.jpg'],
      hashrate: '120 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '2760W',
      description: 'Great value Bitcoin miner with 120 TH/s hashrate at an attractive price point.',
    },
    {
      name: 'Bitmain Antminer S19K Pro 115TH',
      slug: 's19k-pro-115th-crypto-asic-miner',
      price: 22400,
      compareAtPrice: 32000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 5,
      isActive: true,
      images: ['/products/s19k-pro-115th.jpg'],
      hashrate: '115 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '2645W',
      description: 'Reliable Bitcoin miner with excellent price-to-performance ratio.',
    },
    {
      name: 'Bitmain Antminer S19K Pro 110TH',
      slug: 's19k-pro-110th-crypto-asic-miner',
      price: 21900,
      compareAtPrice: 30000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 6,
      isActive: true,
      images: ['/products/s19k-pro-120th.jpg'],
      hashrate: '110 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '2530W',
      description: 'Entry-level S19K Pro with solid performance and great efficiency.',
    },
    // S19j Pro Series
    {
      name: 'Bitmain Antminer S19j Pro 104TH',
      slug: 's19j-pro-104th-crypto-asic-miner',
      price: 28490,
      compareAtPrice: 40000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      images: ['/products/s19j-pro-104th.png'],
      hashrate: '104 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3068W',
      description: 'The Antminer S19j Pro offers excellent value with proven performance.',
    },
    // S19 Standard Series
    {
      name: 'Bitmain Antminer S19 86TH',
      slug: 's19-86th-crypto-asic-miner',
      price: 22160,
      compareAtPrice: 32000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 4,
      isActive: true,
      images: ['/products/s19-95th.png'],
      hashrate: '86 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '2967W',
      description: 'Budget-friendly Bitcoin miner with reliable performance.',
    },
    // IceRiver Kaspa Miners
    {
      name: 'IceRiver KS5 PRO Kaspa Miner 21TH',
      slug: 'iceriver-ks5-pro-kaspa-miner-21th',
      price: 34700,
      compareAtPrice: 50000,
      vendor: 'IceRiver',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      isFeatured: true,
      images: ['/products/ks5-kaspa.jpg'],
      hashrate: '21 TH/s',
      algorithm: 'KHeavyHash',
      powerConsumption: '3200W',
      description: 'The IceRiver KS5 PRO is a powerful Kaspa (KAS) miner, optimized for the KHeavyHash algorithm.',
    },
    {
      name: 'IceRiver KS5 Kaspa Miner 18TH',
      slug: 'iceriver-ks5-kaspa-miner-18th',
      price: 27700,
      compareAtPrice: 40000,
      vendor: 'IceRiver',
      categoryId: newMiners.id,
      stock: 4,
      isActive: true,
      images: ['/products/ks5-kaspa.jpg'],
      hashrate: '18 TH/s',
      algorithm: 'KHeavyHash',
      powerConsumption: '2700W',
      description: 'The IceRiver KS5 delivers excellent Kaspa mining performance.',
    },
    {
      name: 'IceRiver KAS KS5M 15TH',
      slug: 'iceriver-ks5m-kaspa-miner-15th',
      price: 20668,
      compareAtPrice: 30000,
      vendor: 'IceRiver',
      categoryId: newMiners.id,
      stock: 5,
      isActive: true,
      images: ['/products/ks5-kaspa.jpg'],
      hashrate: '15 TH/s',
      algorithm: 'KHeavyHash',
      powerConsumption: '2250W',
      description: 'Mid-range Kaspa miner with excellent efficiency.',
    },
    {
      name: 'IceRiver KAS KS5L 12TH',
      slug: 'iceriver-ks5l-kaspa-miner-12th',
      price: 16824,
      compareAtPrice: 25000,
      vendor: 'IceRiver',
      categoryId: newMiners.id,
      stock: 6,
      isActive: true,
      images: ['/products/ks5-kaspa.jpg'],
      hashrate: '12 TH/s',
      algorithm: 'KHeavyHash',
      powerConsumption: '1800W',
      description: 'Entry-level Kaspa miner at an affordable price point.',
    },
    // Scrypt Miners (LTC/DOGE)
    {
      name: 'Bitmain Antminer L9 15GH Scrypt Miner',
      slug: 'l9-15gh-bitmain-asic-script-miner',
      price: 104000,
      compareAtPrice: 150000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      images: ['/products/l9-scrypt.png'],
      hashrate: '15 GH/s',
      algorithm: 'Scrypt',
      powerConsumption: '3150W',
      description: 'The Antminer L9 is a high-performance Scrypt miner for Litecoin and Dogecoin mining.',
    },
    {
      name: 'Bitmain Antminer L7 9.05GH Scrypt Miner',
      slug: 'l7-9gh-bitmain-asic-script-miner',
      price: 43200,
      compareAtPrice: 65000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      images: ['/products/ltc-doge-scrypt.png'],
      hashrate: '9.05 GH/s',
      algorithm: 'Scrypt',
      powerConsumption: '3425W',
      description: 'The legendary L7 Scrypt miner for Litecoin and Dogecoin.',
    },
    // Alephium Miner
    {
      name: 'Bitmain Antminer AL1 Alephium',
      slug: 'al1-bitmain-alephium-miner',
      price: 205200,
      compareAtPrice: 350000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 1,
      isActive: true,
      images: ['/products/s21.jpg'],
      hashrate: '15.6 TH/s',
      algorithm: 'Blake3',
      powerConsumption: '3300W',
      description: 'The Antminer AL1 is designed for mining Alephium (ALPH) with exceptional efficiency.',
    },
    // Whatsminer products
    {
      name: 'WhatsMiner M60 156TH',
      slug: 'whatsminer-m60-156th',
      price: 48200,
      compareAtPrice: 75000,
      vendor: 'MicroBT',
      categoryId: newMiners.id,
      stock: 5,
      isActive: true,
      isFeatured: true,
      images: ['/products/whatsminer.png'],
      hashrate: '156 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3120W',
      description: 'The WhatsMiner M60 delivers excellent performance with 19.9 W/TH efficiency.',
    },
    {
      name: 'WhatsMiner M50S+ 136TH',
      slug: 'whatsminer-m50s-plus-136th',
      price: 32600,
      compareAtPrice: 50000,
      vendor: 'MicroBT',
      categoryId: newMiners.id,
      stock: 4,
      isActive: true,
      images: ['/products/whatsminer.png'],
      hashrate: '136 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3264W',
      description: 'The WhatsMiner M50S+ offers great efficiency at 24 W/TH.',
    },
    {
      name: 'WhatsMiner M50 120TH',
      slug: 'whatsminer-m50-120th',
      price: 31240,
      compareAtPrice: 50000,
      vendor: 'MicroBT',
      categoryId: newMiners.id,
      stock: 6,
      isActive: true,
      images: ['/products/whatsminer.png'],
      hashrate: '120 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3480W',
      description: 'Reliable mid-range Bitcoin miner with 29 W/TH efficiency.',
    },
    // Second Hand Miners - adjusted prices
    {
      name: 'WhatsMiner M50s 130TH (Used)',
      slug: 'whatsminer-m50s-130th-used',
      price: 28999,
      compareAtPrice: 40000,
      vendor: 'MicroBT',
      categoryId: secondHand.id,
      stock: 2,
      isActive: true,
      images: ['/products/whatsminer-m50s-130th.png'],
      hashrate: '130 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3380W',
      description: 'Pre-owned WhatsMiner M50s in excellent condition. Fully tested and ready to mine.',
    },
    {
      name: 'WhatsMiner M50s 124TH (Used)',
      slug: 'whatsminer-m50s-124th-used',
      price: 26999,
      compareAtPrice: 38000,
      vendor: 'MicroBT',
      categoryId: secondHand.id,
      stock: 3,
      isActive: true,
      images: ['/products/whatsminer-m50s-124th.png'],
      hashrate: '124 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3224W',
      description: 'Quality pre-owned WhatsMiner M50s. Tested and verified.',
    },
    {
      name: 'WhatsMiner M31S 88TH (Used)',
      slug: 'whatsminer-m31s-88th-used',
      price: 18999,
      compareAtPrice: 28000,
      vendor: 'MicroBT',
      categoryId: secondHand.id,
      stock: 4,
      isActive: true,
      images: ['/products/whatsminer-m31s.png'],
      hashrate: '88 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3344W',
      description: 'Budget-friendly used Bitcoin miner. Perfect for beginners.',
    },
    {
      name: 'WhatsMiner M30S+ 88TH (Used)',
      slug: 'whatsminer-m30s-plus-88th-used',
      price: 16999,
      compareAtPrice: 25000,
      vendor: 'MicroBT',
      categoryId: secondHand.id,
      stock: 5,
      isActive: true,
      images: ['/products/whatsminer-m30s-plus.png'],
      hashrate: '88 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3344W',
      description: 'Great value used Bitcoin miner at an unbeatable price.',
    },
    // New Flagship Models
    {
      name: 'Bitmain Antminer S21 XP 270TH',
      slug: 's21-xp-270th-crypto-asic-miner',
      price: 104500,
      compareAtPrice: 130000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      isFeatured: true,
      images: ['/products/s21-xp.webp'],
      hashrate: '270 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3645W',
      description: 'The Bitmain Antminer S21 XP is the newest flagship Bitcoin miner with industry-leading 270 TH/s hashrate and exceptional 13.5 J/TH efficiency.',
    },
    {
      name: 'Bitmain Antminer S21+ 216TH',
      slug: 's21-plus-216th-crypto-asic-miner',
      price: 68300,
      compareAtPrice: 85000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      isFeatured: true,
      images: ['/products/s21-plus.webp'],
      hashrate: '216 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3564W',
      description: 'The Bitmain Antminer S21+ offers excellent performance at 216 TH/s with 16.5 J/TH efficiency. Perfect balance of power and value.',
    },
    {
      name: 'Bitmain Antminer S23 211TH',
      slug: 's23-211th-crypto-asic-miner',
      price: 169700,
      compareAtPrice: 200000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 1,
      isActive: true,
      isFeatured: true,
      images: ['/products/s23.webp'],
      hashrate: '211 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3450W',
      description: 'The Bitmain Antminer S23 is the latest generation Bitcoin miner with cutting-edge efficiency at 16.3 J/TH. Premium mining performance.',
    },
    // Canaan Avalon Series
    {
      name: 'Canaan Avalon Q Bitcoin Miner',
      slug: 'canaan-avalon-q-bitcoin-miner',
      price: 36500,
      compareAtPrice: 45000,
      vendor: 'Canaan',
      categoryId: newMiners.id,
      stock: 4,
      isActive: true,
      images: ['/products/avalon-q.webp'],
      hashrate: '90 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '2700W',
      description: 'The Canaan Avalon Q is a reliable alternative to Bitmain miners. Excellent build quality and solid performance.',
    },
    {
      name: 'Canaan Avalon Mini 3',
      slug: 'canaan-avalon-mini-3',
      price: 22499,
      compareAtPrice: 28000,
      vendor: 'Canaan',
      categoryId: newMiners.id,
      stock: 5,
      isActive: true,
      images: ['/products/avalon-mini-3.webp'],
      hashrate: '37.5 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '1200W',
      description: 'Compact Bitcoin miner perfect for home use. Quiet operation and low power consumption.',
    },
    {
      name: 'Canaan Avalon Nano 3s',
      slug: 'canaan-avalon-nano-3s',
      price: 5799,
      compareAtPrice: 7500,
      vendor: 'Canaan',
      categoryId: newMiners.id,
      stock: 10,
      isActive: true,
      images: ['/products/avalon-nano-3s.png'],
      hashrate: '4 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '170W',
      description: 'Ultra-compact solo Bitcoin miner. Perfect for lottery mining from home with minimal noise and power usage.',
    },
    // IceRiver KS7
    {
      name: 'IceRiver KS7 Kaspa Miner 20TH',
      slug: 'iceriver-ks7-kaspa-miner-20th',
      price: 52650,
      compareAtPrice: 65000,
      vendor: 'IceRiver',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      isFeatured: true,
      images: ['/products/ks5m.webp'],
      hashrate: '20 TH/s',
      algorithm: 'KHeavyHash',
      powerConsumption: '3200W',
      description: 'The IceRiver KS7 is a high-capacity Kaspa miner with excellent hashrate for serious KAS mining operations.',
    },
    // Elphapex Scrypt Miner
    {
      name: 'Elphapex DG1+ Scrypt Miner',
      slug: 'elphapex-dg1-plus-scrypt-miner',
      price: 89950,
      compareAtPrice: 110000,
      vendor: 'Elphapex',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      isFeatured: true,
      images: ['/products/elphapex-dg1.png'],
      hashrate: '14 GH/s',
      algorithm: 'Scrypt',
      powerConsumption: '3600W',
      description: 'The Elphapex DG1+ is a powerful Scrypt miner for Litecoin and Dogecoin. Competes directly with the Antminer L9.',
    },
    // Accessories
    {
      name: 'Cryptominer Liquid Cooling Solution',
      slug: 'cryptominer-liquid-cooling-solution',
      price: 45000,
      vendor: 'Outsourced CTO',
      categoryId: accessories.id,
      stock: 10,
      isActive: true,
      images: ['/products/liquid-cooling.jpg'],
      description: 'Professional liquid cooling solution for cryptocurrency mining rigs. Dramatically reduces noise and improves efficiency.',
    },
  ]

  console.log('Creating products...')
  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    })
  }
  console.log(`Created ${products.length} products`)

  console.log('Seeding complete!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
