import { PrismaClient } from '@prisma/client'
import { hash } from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding database...')

  // Create admin user
  const adminPassword = await hash(process.env.ADMIN_PASSWORD || 'admin123', 12)
  const admin = await prisma.user.upsert({
    where: { email: process.env.ADMIN_EMAIL || 'admin@shopcrypto.co.za' },
    update: {},
    create: {
      email: process.env.ADMIN_EMAIL || 'admin@shopcrypto.co.za',
      name: 'Admin',
      password: adminPassword,
      role: 'ADMIN',
    },
  })
  console.log('Admin user created:', admin.email)

  // Create categories
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: 'new-miners' },
      update: {},
      create: {
        name: 'New Miners',
        slug: 'new-miners',
        description: 'Brand new ASIC miners from top manufacturers',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'second-hand-miners' },
      update: {},
      create: {
        name: 'Second Hand Miners',
        slug: 'second-hand-miners',
        description: 'Quality pre-owned miners at great prices',
      },
    }),
    prisma.category.upsert({
      where: { slug: 'accessories' },
      update: {},
      create: {
        name: 'Accessories',
        slug: 'accessories',
        description: 'Cooling, cables, and mining essentials',
      },
    }),
  ])
  console.log('Categories created:', categories.map(c => c.name).join(', '))

  const [newMiners, secondHand, accessories] = categories

  // Create products (from actual shopcrypto.co.za inventory)
  const products = [
    // New Miners
    {
      name: 'Bitmain Antminer S21 200TH',
      slug: 's21-200th-crypto-asic-miner',
      price: 103999,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 5,
      isActive: true,
      isFeatured: true,
      hashrate: '200 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3500W',
      description: 'The Bitmain Antminer S21 200TH is one of the most powerful Bitcoin miners available. With a hashrate of 200 TH/s and power efficiency of 17.5 J/TH, this miner delivers exceptional performance for serious mining operations.',
    },
    {
      name: 'Bitmain Antminer S21 190TH',
      slug: 's21-190th-crypto-asic-miner',
      price: 99999,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      isFeatured: true,
      hashrate: '190 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3290W',
      description: 'The Bitmain Antminer S21 190TH delivers outstanding Bitcoin mining performance with industry-leading efficiency.',
    },
    {
      name: 'Bitmain Antminer S21 PRO 234TH',
      slug: 's21-pro-234th-crypto-asic-miner',
      price: 115000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      isFeatured: true,
      hashrate: '234 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3510W',
      description: 'The flagship Bitmain Antminer S21 PRO with 234 TH/s hashrate. The most powerful consumer Bitcoin miner available.',
    },
    {
      name: 'Bitmain Antminer S19 XP 140TH',
      slug: 's19-xp-140th-crypto-asic-miner',
      price: 99000,
      compareAtPrice: 116000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 4,
      isActive: true,
      isFeatured: true,
      hashrate: '140 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3010W',
      description: 'The Bitmain Antminer S19 XP 140TH offers excellent hashrate with improved power efficiency for Bitcoin mining.',
    },
    {
      name: 'Bitmain Antminer S19j Pro+ 120TH',
      slug: 's19j-pro-plus-120th',
      price: 69999,
      compareAtPrice: 79999,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 6,
      isActive: true,
      hashrate: '120 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '2760W',
      description: 'The Bitmain Antminer S19j Pro+ 120TH delivers solid performance and efficiency for Bitcoin mining operations.',
    },
    {
      name: 'Bitmain Antminer S19k Pro 120TH',
      slug: 's19k-pro-120th-crypto-asic-miner',
      price: 49999,
      compareAtPrice: 75000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 8,
      isActive: true,
      isFeatured: true,
      hashrate: '120 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '2760W',
      description: 'Great value Bitcoin miner with 120 TH/s hashrate at an attractive price point.',
    },
    {
      name: 'Bitmain Antminer S19k Pro 115TH',
      slug: 's19k-pro-115th-crypto-asic-miner',
      price: 45000,
      compareAtPrice: 71000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 5,
      isActive: true,
      hashrate: '115 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '2645W',
      description: 'Reliable Bitcoin miner with excellent price-to-performance ratio.',
    },
    {
      name: 'Bitmain Antminer S19 Pro 110TH',
      slug: 's19-pro-110th-crypto-asic-miner',
      price: 59999,
      compareAtPrice: 109000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      hashrate: '110 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3250W',
      description: 'The legendary Bitmain Antminer S19 Pro with proven reliability and solid hashrate.',
    },
    {
      name: 'Bitmain Antminer S19 Pro 105TH',
      slug: 's19-pro-105th-crypto-asic-miner',
      price: 59999,
      compareAtPrice: 137000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 4,
      isActive: true,
      hashrate: '105 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3150W',
      description: 'Reliable professional-grade Bitcoin miner from Bitmain.',
    },
    {
      name: 'Bitmain Antminer S19j Pro 104TH',
      slug: 's19j-pro-104th-crypto-asic-miner',
      price: 55500,
      compareAtPrice: 155000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      hashrate: '104 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3068W',
      description: 'The Antminer S19j Pro offers excellent value with proven performance.',
    },
    {
      name: 'Bitmain Antminer S19j Pro 100TH',
      slug: 's19j-pro-100th-crypto-asic-miner',
      price: 49999,
      compareAtPrice: 99999,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 5,
      isActive: true,
      hashrate: '100 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '2950W',
      description: 'Entry-level professional Bitcoin miner with solid performance.',
    },
    {
      name: 'Bitmain Antminer S19 110TH',
      slug: 's19-110th-crypto-asic-miner',
      price: 59999,
      compareAtPrice: 67999,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      hashrate: '110 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3250W',
      description: 'Standard Antminer S19 with 110 TH/s hashrate.',
    },
    {
      name: 'Bitmain Antminer S19 95TH',
      slug: 's19-95th-crypto-asic-miner',
      price: 38999,
      compareAtPrice: 39999,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 6,
      isActive: true,
      hashrate: '95 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3250W',
      description: 'Budget-friendly Bitcoin miner with reliable performance.',
    },
    {
      name: 'Bitmain Antminer S19 90TH',
      slug: 's19-90th-crypto-asic-miner',
      price: 32999,
      compareAtPrice: 37500,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 4,
      isActive: true,
      hashrate: '90 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3105W',
      description: 'Affordable entry into Bitcoin mining with the S19 90TH.',
    },
    {
      name: 'IceRiver KS5 Kaspa Miner 21TH',
      slug: 'iceriver-ks5-kaspa-miner-21th',
      price: 75000,
      compareAtPrice: 90000,
      vendor: 'IceRiver',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      isFeatured: true,
      hashrate: '21 TH/s',
      algorithm: 'KHeavyHash',
      powerConsumption: '3200W',
      description: 'The IceRiver KS5 is a powerful Kaspa (KAS) miner, optimized for the KHeavyHash algorithm.',
    },
    {
      name: 'Bitmain Antminer L9 16GH Script Miner',
      slug: 'l9-16gh-bitmain-asic-script-miner',
      price: 275000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      hashrate: '16 GH/s',
      algorithm: 'Scrypt',
      powerConsumption: '3360W',
      description: 'The Antminer L9 is a high-performance Scrypt miner for Litecoin and Dogecoin mining.',
    },
    {
      name: 'Bitmain LTC/Doge Script Miner 14GH',
      slug: 'ltc-doge-script-miner-14gh',
      price: 219999,
      compareAtPrice: 250000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      hashrate: '14 GH/s',
      algorithm: 'Scrypt',
      powerConsumption: '2800W',
      description: 'Mine Litecoin and Dogecoin with this efficient Scrypt ASIC miner.',
    },
    {
      name: 'Bitmain Al1 15.6TH Alpha Miner Alephium',
      slug: 'al1-15-6th-alpha-miner-alephium',
      price: 750000,
      vendor: 'Bitmain',
      categoryId: newMiners.id,
      stock: 1,
      isActive: true,
      hashrate: '15.6 TH/s',
      algorithm: 'Blake3',
      powerConsumption: '3300W',
      description: 'The Antminer AL1 is designed for mining Alephium (ALPH) with exceptional efficiency.',
    },
    // Whatsminer products
    {
      name: 'WhatsMiner M66s 298TH',
      slug: 'whatsminer-m66s-298th',
      price: 196147,
      compareAtPrice: 267000,
      vendor: 'MicroBT',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      isFeatured: true,
      hashrate: '298 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '5493W',
      description: 'The WhatsMiner M66s 298TH is one of the highest hashrate Bitcoin miners available.',
    },
    {
      name: 'WhatsMiner M66s 270TH',
      slug: 'whatsminer-m66s-270th',
      price: 181999,
      compareAtPrice: 250000,
      vendor: 'MicroBT',
      categoryId: newMiners.id,
      stock: 2,
      isActive: true,
      hashrate: '270 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '4995W',
      description: 'High-performance Bitcoin mining with the WhatsMiner M66s.',
    },
    {
      name: 'WhatsMiner M63 334TH',
      slug: 'whatsminer-m63-334th',
      price: 121999,
      compareAtPrice: 2500000,
      vendor: 'MicroBT',
      categoryId: newMiners.id,
      stock: 1,
      isActive: true,
      hashrate: '334 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '6171W',
      description: 'The WhatsMiner M63 delivers exceptional hashrate for industrial Bitcoin mining.',
    },
    {
      name: 'WhatsMiner M60s 186TH',
      slug: 'whatsminer-m60s-186th',
      price: 137179,
      compareAtPrice: 149000,
      vendor: 'MicroBT',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      hashrate: '186 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3441W',
      description: 'Efficient and powerful Bitcoin mining with the WhatsMiner M60s.',
    },
    {
      name: 'WhatsMiner M60s 170TH',
      slug: 'whatsminer-m60s-170th',
      price: 128999,
      compareAtPrice: 149000,
      vendor: 'MicroBT',
      categoryId: newMiners.id,
      stock: 4,
      isActive: true,
      hashrate: '170 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3145W',
      description: 'Solid performance and efficiency with the WhatsMiner M60s 170TH.',
    },
    {
      name: 'WhatsMiner M60 172TH',
      slug: 'whatsminer-m60-172th',
      price: 122999,
      compareAtPrice: 149000,
      vendor: 'MicroBT',
      categoryId: newMiners.id,
      stock: 3,
      isActive: true,
      hashrate: '172 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3440W',
      description: 'The WhatsMiner M60 offers great value with 172 TH/s hashrate.',
    },
    {
      name: 'WhatsMiner M60 156TH',
      slug: 'whatsminer-m60-156th',
      price: 114999,
      compareAtPrice: 149000,
      vendor: 'MicroBT',
      categoryId: newMiners.id,
      stock: 5,
      isActive: true,
      hashrate: '156 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3120W',
      description: 'Budget-friendly high-performance Bitcoin miner from MicroBT.',
    },
    {
      name: 'WhatsMiner M50 126TH',
      slug: 'whatsminer-m50-126th',
      price: 85999,
      compareAtPrice: 100000,
      vendor: 'MicroBT',
      categoryId: newMiners.id,
      stock: 6,
      isActive: true,
      hashrate: '126 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3276W',
      description: 'Reliable mid-range Bitcoin miner with 126 TH/s hashrate.',
    },
    // Second Hand Miners
    {
      name: 'WhatsMiner M50s 130TH (Used)',
      slug: 'whatsminer-m50s-130th-used',
      price: 87999,
      compareAtPrice: 105000,
      vendor: 'MicroBT',
      categoryId: secondHand.id,
      stock: 2,
      isActive: true,
      hashrate: '130 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3380W',
      description: 'Pre-owned WhatsMiner M50s in excellent condition. Fully tested and ready to mine.',
    },
    {
      name: 'WhatsMiner M50s 124TH (Used)',
      slug: 'whatsminer-m50s-124th-used',
      price: 82999,
      compareAtPrice: 100000,
      vendor: 'MicroBT',
      categoryId: secondHand.id,
      stock: 3,
      isActive: true,
      hashrate: '124 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3224W',
      description: 'Quality pre-owned WhatsMiner M50s. Tested and verified.',
    },
    {
      name: 'WhatsMiner M31S 88TH (Used)',
      slug: 'whatsminer-m31s-88th-used',
      price: 49999,
      compareAtPrice: 65000,
      vendor: 'MicroBT',
      categoryId: secondHand.id,
      stock: 4,
      isActive: true,
      hashrate: '88 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3344W',
      description: 'Budget-friendly used Bitcoin miner. Perfect for beginners.',
    },
    {
      name: 'WhatsMiner M30S+ 88TH (Used)',
      slug: 'whatsminer-m30s-plus-88th-used',
      price: 26152,
      compareAtPrice: 36999,
      vendor: 'MicroBT',
      categoryId: secondHand.id,
      stock: 5,
      isActive: true,
      hashrate: '88 TH/s',
      algorithm: 'SHA-256',
      powerConsumption: '3344W',
      description: 'Great value used Bitcoin miner at an unbeatable price.',
    },
    // Accessories
    {
      name: 'Cryptominer Liquid Cooling Solution',
      slug: 'cryptominer-liquid-cooling-solution',
      price: 45000,
      vendor: 'Outsourced CTO',
      categoryId: accessories.id,
      stock: 10,
      isActive: true,
      description: 'Professional liquid cooling solution for cryptocurrency mining rigs. Dramatically reduces noise and improves efficiency.',
    },
  ]

  console.log('Creating products...')
  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    })
  }
  console.log(`Created ${products.length} products`)

  console.log('Seeding complete!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
